image: gradle:8.6.0-jdk21-alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  SPRING_PROFILES_ACTIVE: dev
  SERVER_PORT: 9091
  DEBUG_PORT: 9092
  SPRING_DB_URL: jdbc:postgresql://192.168.7.12:5432/postgres
  SPRING_DB_USERNAME: postgres
  SPRING_DB_PASSWORD: postgres
  LIQUIBASE_DEFAULT_SCHEMA: public
  DOCKER_IMAGE_NAME: $CI_REGISTRY/$DOCKER_USERNAME/eco-pharma-warehouse
  DOCKER_TAG: latest
  DOCKER_TLS_CERTDIR: ""

stages:
  - gradle-build
  - publish
  - deploy

cache:
  key: "$CI_COMMIT_REF_SLUG-gradle-cache"
  paths:
    - ~/.gradle/caches/
    - ~/.gradle/wrapper/
  policy: pull-push
  when: always

# Stage 1: Build the JAR file
build:
  stage: gradle-build
  script:
    - gradle clean bootJar
  artifacts:
    paths:
      - build/libs/*.jar
      - docker-compose-wms.yml
    expire_in: 1 week
  only:
    - main
    - dev

# Stage 2: Publish Docker image
publish:
  stage: publish
  image: docker:latest
  services:
    - docker:24.0.6-dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
  before_script:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" $CI_REGISTRY
    - docker buildx create --use
  script:
    - docker buildx build \
      --build-arg SPRING_PROFILE=$SPRING_PROFILES_ACTIVE \
      --build-arg SERVER_PORT=$SERVER_PORT \
      --build-arg DEBUG_PORT=$DEBUG_PORT \
      --build-arg JAVA_OPTS="-Xms128m -Xmx512m" \
      --build-arg EXTRA_ARGS="" \
      --tag $DOCKER_IMAGE_NAME:$DOCKER_TAG \
      --tag $DOCKER_IMAGE_NAME:$CI_COMMIT_SHA \
      --push .
  only:
    - main
    - dev

# Stage 3: Deploy using Docker Compose
deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan "$SERVER_IP" >> ~/.ssh/known_hosts
  script:
    - ssh $SERVER_USER@$SERVER_IP "mkdir -p gitlab-runner-api/eco-pharma-api && chmod 755 gitlab-runner-api/eco-pharma-api"
    - scp docker-compose-wms.yml $SERVER_USER@$SERVER_IP:gitlab-runner-api/eco-pharma-api
    - ssh $SERVER_USER@$SERVER_IP <<'EOF'
      cd gitlab-runner-api/eco-pharma-api
      docker compose -f docker-compose-wms.yml down || true
      docker compose -f docker-compose-wms.yml pull
      docker compose -f docker-compose-wms.yml up -d
      docker image prune -f --filter "until=24h" || true
      docker container prune -f || true
      docker system prune -f --volumes --filter "label!=keep=true" || true
      EOF
  only:
    - main
    - dev
