version: '3.8'

services:
  # Spring Boot Application
  wms-service:
    image: duoluz/eco-pharma-warehouse:latest-dev # Use the latest tag if TAG is not provided
    container_name: wms-service
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - TZ=Asia/Tashkent
    ports:
      - "9091:9091"
    networks:
      - shared-network-pharm
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - wm-service-dev-logs:/opt/app/logs
volumes:
  wm-service-dev-logs:
    driver: local

networks:
  shared-network-pharm:
    external: true
    name: shared-network-pharm