version: '3.8'

services:
  # Spring Boot Application
  wms-service:
    image: duoluz/eco-pharma-warehouse:latest-stage # Use the latest tag if TAG is not provided
    container_name: wms-service
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=stage
      - TZ=Asia/Tashkent
    ports:
      - "9091:9091"
    networks:
      - ecopharm-data
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

networks:
  ecopharm-data:
    driver: bridge