version: '3.8'

services:
  # PostgreSQL Database
  wms-postgres:
    image: postgres:latest
    container_name: pharm-wms-postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pg-data-wms:/var/lib/postgresql/data  # Corrected volume reference
    ports:
      - "5430:5432"
    networks:
      - ecopharm-data

volumes:
  pg-data-wms:
    driver: local  # Volume name changed to pg-data-wms

networks:
  ecopharm-data:
    driver: bridge
