version: '3.8'

services:
  # Spring Boot Application
  wms-service-test:
    image: duoluz/eco-pharma-warehouse:latest-test # Use the latest tag if TAG is not provided
    container_name: wms-service-test
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - TZ=Asia/Tashkent
    ports:
      - "1091:1091"
    networks:
      - ecopharm-data
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - wm-service-test-logs:/opt/app/logs
volumes:
  wm-service-test-logs:
    driver: local

networks:
  ecopharm-data:
    driver: bridge