version: '3.8'

services:
  # Spring Boot Application
  wms-service:
    image: duoluz/eco-pharma-warehouse:latest-stage # Use the latest tag if TAG is not provided
    container_name: eco-pharma-wms-service
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=stage
    ports:
      - "9091:9091"
    networks:
      - ecopharm-data

volumes:
  pg-data:
    driver: local

networks:
  ecopharm-data:
    driver: bridge