INSERT INTO sector (
    id,
    created_at,
    updated_at,
    status,
    created_by,
    updated_by,
    name,
    description
) VALUES
      (8001, NOW(), NOW(), 'CREATED', 1, 1, 'Sector Alpha', 'Primary storage area for high-demand goods.'),
      (8002, NOW(), NOW(), 'CREATED', 1, 1, 'Sector Beta', 'Secondary storage area for medium-demand goods.'),
      (8003, NOW(), NOW(), 'DELETED', 1, 1, 'Sector Gamma', 'Reserved for seasonal inventory.'),
      (8004, NOW(), NOW(), 'CREATED', 1, 1, 'Sector Delta', 'High-security storage for sensitive items.'),
      (8005, NOW(), NOW(), 'CREATED', 1, 1, 'Sector Epsilon', 'General-purpose storage area.'),
      (8006, NOW(), NOW(), 'DELETED', 1, 1, 'Sector Zeta', 'Temporary overflow storage.'),
      (8007, NOW(), NOW(), 'CREATED', 1, 1, 'Sector Eta', 'Storage for perishable goods.'),
      (8008, NOW(), NOW(), 'CREATED', 1, 1, 'Sector Theta', 'Dedicated to small-item storage.'),
      (8009, NOW(), NOW(), 'CREATED', 1, 1, 'Sector Iota', 'Bulk storage for large items.'),
      (8010, NOW(), NOW(), 'DELETED', 1, 1, 'Sector Kappa', 'Under maintenance, not in use.'),
      (8011, NOW(), NOW(), 'CREATED', 1, 1, 'Sector Lambda', 'Storage for electronics and fragile items.'),
      (8012, NOW(), NOW(), 'CREATED', 1, 1, 'Sector Mu', 'Reserved for future expansion.'),
      (8013, NOW(), NOW(), 'DELETED', 1, 1, 'Sector Nu', 'Decommissioned storage area.'),
      (8014, NOW(), NOW(), 'CREATED', 1, 1, 'Sector Xi', 'High-turnover goods storage.'),
      (8015, NOW(), NOW(), 'CREATED', 1, 1, 'Sector Omicron', 'Storage for hazardous materials.'),
      (8016, NOW(), NOW(), 'DELETED', 1, 1, 'Sector Pi', 'Closed for renovations.'),
      (8017, NOW(), NOW(), 'CREATED', 1, 1, 'Sector Rho', 'Cold storage for temperature-sensitive goods.'),
      (8018, NOW(), NOW(), 'CREATED', 1, 1, 'Sector Sigma', 'Storage for oversized equipment.'),
      (8019, NOW(), NOW(), 'CREATED', 1, 1, 'Sector Tau', 'Dedicated to customer returns processing.'),
      (8020, NOW(), NOW(), 'DELETED', 1, 1, 'Sector Upsilon', 'Out-of-service due to structural issues.');