server:
  port: 1091

spring:
  datasource:
    url: jdbc:postgresql://192.168.100.193:5434/wms
    username: postgres
    password: postgres
  jpa:
    show-sql: true
  liquibase:
    default-schema: public
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.rivermed.uz/realms/eco-pharma
          jwk-set-uri: https://keycloak.rivermed.uz/realms/eco-pharma/protocol/openid-connect/certs
  rabbitmq:
    host: 192.168.100.194
    port: 5671
    username: admin
    password: admin!123
    ssl:
      enabled: true
      algorithm: TLSv1.2
      validate-server-certificate: false

keycloak:
  realm: eco-pharma
  auth-server-url: https://keycloak.rivermed.uz
  client-id: eco-pharma
  client-secret: QG25UNd5aOrrmttgOAkRQwWZZUag62ko
  public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjCHpICM88DjY+mK8CIYohjJpM2+wekoUv87da1B0bYSz2pnvlmIATm70X9SGj3kH+3t5S3vtXtxH9FCX2Ek32zQ2AWmp7ydO0focpj9fdlG++vHV3yNudkK0eOG/YaqE1CZ33UpCeyxV6vZDK439koWhj1JDNqKLWD/UWj2g+fvMYa9/0i5Jm2dLuxNanjBNW8r9OyU26GEDMsh5PEI3I3GqnTlAmTGBPpWfN7H4eKyHd/lom9PHd0RxtbuKtWjy/lP9RLt1RQUlJai4bywasxyKcVuusbfeB82XclRBr2U/ooMZFTRGfxYq7gsonMIvyeb8RotFsFENgIntKgGT/wIDAQAB


eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://192.168.100.193:8098/eureka/
    healthcheck:
      enabled: true
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 10

springdoc:
  api-docs:
    enabled: true
    path: /api/v1/wms/v3/api-docs
  swagger-ui:
    path: /api/v1/wms/swagger-ui
    enabled: true
    try-it-out-enabled: true
    operations-sorter: method

minio:
  endpoint: https://storage.rivermed.uz
  access-key: 4eTbVd5A0wCbisN8bP0b
  secret-key: 7Wh2bLKVRR8alNvAEmZi7RHx7eggWGtsEuaZnBJ1
  bucket: backups

postgres:
  container:
    name: eco-pharma-warehouse-postgres

backup:
  useShell: false

logging:
  config: classpath:log4j2-stage.xml
  threshold:
    console: error

logstash:
  host: 192.168.100.141
  port: 5000