INSERT INTO characteristic (
    id,
    created_at,
    updated_at,
    status,
    created_by,
    updated_by,
    name,
    description,
    type
) VALUES
      (9001, NOW(), NOW(), 'CREATED', 1, 1, 'Height', 'Height of the object in meters', 'TEXT'),
      (9002, NOW(), NOW(), 'CREATED', 1, 1, 'Width', 'Width of the object in meters', 'TEXT'),
      (9003, NOW(), NOW(), 'DELETED', 1, 1, 'Depth', 'Depth of the object in meters', 'TEXT'),
      (9004, NOW(), NOW(), 'CREATED', 1, 1, 'Weight', 'Maximum weight capacity in kilograms', 'TEXT'),
      (9005, NOW(), NOW(), 'CREATED', 1, 1, 'Volume', 'Maximum volume capacity in cubic meters', 'TEXT'),
      (9006, NOW(), NOW(), 'DELETED', 1, 1, 'Temperature', 'Temperature range for storage', 'TEXT'),
      (9007, NOW(), NOW(), 'CREATED', 1, 1, 'Humidity', 'Humidity level for storage', 'TEXT'),
      (9008, NOW(), NOW(), 'CREATED', 1, 1, 'Load Capacity', 'Maximum load capacity for racks', 'TEXT'),
      (9009, NOW(), NOW(), 'CREATED', 1, 1, 'Material', 'Material used for construction', 'TEXT'),
      (9010, NOW(), NOW(), 'DELETED', 1, 1, 'Color', 'Color of the object', 'TEXT'),
      (9011, NOW(), NOW(), 'CREATED', 1, 1, 'Length', 'Length of the object in meters', 'TEXT'),
      (9012, NOW(), NOW(), 'CREATED', 1, 1, 'Thickness', 'Thickness of the material in millimeters', 'TEXT'),
      (9013, NOW(), NOW(), 'DELETED', 1, 1, 'Power Consumption', 'Energy consumption in watts', 'TEXT'),
      (9014, NOW(), NOW(), 'CREATED', 1, 1, 'Voltage', 'Operating voltage in volts', 'TEXT'),
      (9015, NOW(), NOW(), 'CREATED', 1, 1, 'Capacity', 'Storage capacity in liters', 'TEXT'),
      (9016, NOW(), NOW(), 'DELETED', 1, 1, 'Speed', 'Operating speed in meters per second', 'TEXT'),
      (9017, NOW(), NOW(), 'CREATED', 1, 1, 'Efficiency', 'Energy efficiency rating', 'TEXT'),
      (9018, NOW(), NOW(), 'CREATED', 1, 1, 'Durability', 'Lifespan of the object in years', 'TEXT'),
      (9019, NOW(), NOW(), 'CREATED', 1, 1, 'Flexibility', 'Ability to adapt to different conditions', 'TEXT'),
      (9020, NOW(), NOW(), 'DELETED', 1, 1, 'Transparency', 'Level of transparency of the material', 'TEXT');