INSERT INTO product (
    id,
    created_at,
    updated_at,
    status,
    created_by,
    updated_by,
    name,
    description,
    product_type,
    quantity
) VALUES
      (8001, NOW(), NOW(), 'CREATED', 1, 1, 'Laptop Pro X1', 'High-performance laptop with 16GB RAM', 'electronic', 50),
      (8002, NOW(), NOW(), 'CREATED', 1, 1, 'Smartphone Z20', 'Latest smartphone with 5G support', 'electronic', 100),
      (8003, NOW(), NOW(), 'DELETED', 1, 1, 'Wireless Earbuds', 'Noise-cancelling wireless earbuds', 'electronic', 0),
      (8004, NOW(), NOW(), 'CREATED', 1, 1, 'Organic Apples', 'Fresh organic apples from local farms', 'food', 200),
      (8005, NOW(), NOW(), 'CREATED', 1, 1, 'Whole Grain Bread', 'Healthy whole grain bread', 'food', 150),
      (8006, NOW(), NOW(), 'DELETED', 1, 1, 'Cotton T-Shirt', 'Comfortable cotton t-shirt in various colors', 'clothing', 0),
      (8007, NOW(), NOW(), 'CREATED', 1, 1, 'LED Desk Lamp', 'Adjustable LED desk lamp with USB port', 'electronic', 75),
      (8008, NOW(), NOW(), 'CREATED', 1, 1, 'Dark Chocolate Bar', 'Rich dark chocolate bar with 70% cocoa', 'food', 300),
      (8009, NOW(), NOW(), 'CREATED', 1, 1, 'Running Shoes', 'Lightweight running shoes for athletes', 'clothing', 40),
      (8010, NOW(), NOW(), 'DELETED', 1, 1, 'Bluetooth Speaker', 'Portable Bluetooth speaker with bass boost', 'electronic', 0),
      (8011, NOW(), NOW(), 'CREATED', 1, 1, 'Beef Steak', 'Premium beef steak for grilling', 'food', 60),
      (8012, NOW(), NOW(), 'CREATED', 1, 1, 'Winter Jacket', 'Warm winter jacket with hood', 'clothing', 25),
      (8013, NOW(), NOW(), 'DELETED', 1, 1, 'Mechanical Keyboard', 'RGB mechanical keyboard for gaming', 'electronic', 0),
      (8014, NOW(), NOW(), 'CREATED', 1, 1, 'Orange Juice', 'Freshly squeezed orange juice', 'food', 100),
      (8015, NOW(), NOW(), 'CREATED', 1, 1, 'Jeans', 'Slim-fit jeans for men', 'clothing', 50),
      (8016, NOW(), NOW(), 'DELETED', 1, 1, 'External Hard Drive', '1TB external hard drive for backups', 'electronic', 0),
      (8017, NOW(), NOW(), 'CREATED', 1, 1, 'Milk', 'Fresh milk from local dairy farms', 'food', 200),
      (8018, NOW(), NOW(), 'CREATED', 1, 1, 'Sneakers', 'Casual sneakers for everyday use', 'clothing', 30),
      (8019, NOW(), NOW(), 'CREATED', 1, 1, 'Coffee Beans', 'Premium coffee beans for brewing', 'food', 120),
      (8020, NOW(), NOW(), 'DELETED', 1, 1, 'Gaming Mouse', 'Ergonomic gaming mouse with customizable buttons', 'electronic', 0);