INSERT INTO product (
    id,
    created_at,
    updated_at,
    status,
    created_by,
    updated_by,
    name,
    description,
    product_type,
    quantity
) VALUES
      (8001, NOW(), NOW(), 'CREATED', 1, 1, 'Paracetamol 500mg', 'Pain reliever and fever reducer', 'medicine', 50),
      (8002, NOW(), NOW(), 'CREATED', 1, 1, 'Amoxicillin Capsules', 'Broad-spectrum antibiotic', 'medicine', 100),
      (8003, NOW(), NOW(), 'CREATED', 1, 1, 'Cough Syrup', 'Relieves cough and soothes throat', 'medicine', 0),
      (8004, NOW(), NOW(), 'CREATED', 1, 1, 'Vitamin C Tablets', 'Immune system support', 'supplement', 200),
      (8005, NOW(), NOW(), 'CREATED', 1, 1, 'Omega-3 Fish Oil', 'Supports heart and brain health', 'supplement', 150),
      (8006, NOW(), NOW(), 'CREATED', 1, 1, 'Medical Gloves', 'Latex-free disposable gloves', 'medical_supply', 0),
      (8007, NOW(), NOW(), 'CREATED', 1, 1, 'Antiseptic Solution', 'Disinfectant for wounds', 'medical_supply', 75),
      (8008, NOW(), NOW(), 'CREATED', 1, 1, 'Insulin Pen', 'For diabetes management', 'medical_device', 300),
      (8009, NOW(), NOW(), 'CREATED', 1, 1, 'Surgical Mask', 'Protective face mask', 'medical_supply', 40),
      (8010, NOW(), NOW(), 'CREATED', 1, 1, 'Digital Thermometer', 'Measures body temperature', 'medical_device', 0),
      (8011, NOW(), NOW(), 'CREATED', 1, 1, 'Antacid Tablets', 'Relieves heartburn and indigestion', 'medicine', 60),
      (8012, NOW(), NOW(), 'CREATED', 1, 1, 'Bandages', 'Adhesive wound dressings', 'medical_supply', 25),
      (8013, NOW(), NOW(), 'CREATED', 1, 1, 'Eye Drops', 'Relieves dry and irritated eyes', 'medicine', 0),
      (8014, NOW(), NOW(), 'CREATED', 1, 1, 'Calcium Supplements', 'Supports bone health', 'supplement', 100),
      (8015, NOW(), NOW(), 'CREATED', 1, 1, 'Blood Pressure Monitor', 'Measures blood pressure', 'medical_device', 50),
      (8016, NOW(), NOW(), 'CREATED', 1, 1, 'Saline Solution', 'Sterile solution for hydration', 'medical_supply', 0),
      (8017, NOW(), NOW(), 'CREATED', 1, 1, 'Multivitamin Tablets', 'Daily nutritional supplement', 'supplement', 200),
      (8018, NOW(), NOW(), 'CREATED', 1, 1, 'Compression Stockings', 'Improves blood circulation', 'medical_device', 30),
      (8019, NOW(), NOW(), 'CREATED', 1, 1, 'Zinc Tablets', 'Supports immune function', 'supplement', 120),
      (8020, NOW(), NOW(), 'CREATED', 1, 1, 'Nebulizer Machine', 'Delivers medication to lungs', 'medical_device', 0);
